# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af875818e3dd96c70de13d0796b9a4d97c1aa984b06141c78a9e4bb044867f1571202312f041061e46448b729a5f7a1f6a5a6f3cea4f33ec88d462b2585cd8cb

test:
  secret_key_base: 30a35a268cc9490007b66825faee8414ed86285e2200235ff6988c8575a928ee35ed56de0301a1c2c081a4419908ad8916d03e0c51d06360955302909b05599b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
